parameters:
#    extia_front.example.class: Extia\Bundle\FrontBundle\Example

services:
#    extia_front.example:
#        class: %extia_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
