UserBundle_consultant_list:
    pattern: /
    defaults:
        _controller: 'ExtiaUserBundle:AdminConsultant:list'
        _format: html
    requirements:
        _format: html

UserBundle_consultant_new:
    pattern: /new
    defaults:
        _controller: 'ExtiaUserBundle:AdminConsultant:new'
        _format: html
    requirements:
        _format: html

UserBundle_consultant_timeline:
    pattern: /{Id}/{Url}/timeline
    defaults:
        _controller: 'ExtiaUserBundle:Consultant:timeline'
        _format: html
    requirements:
        id: \d+
        firstname: \w+
        lastname: \w+
        _format: html

UserBundle_consultant_edit:
    pattern: /{Id}/{Url}/edit
    defaults:
        _controller: 'ExtiaUserBundle:AdminConsultant:edit'
        _format: html
    requirements:
        id: \d+
        firstname: \w+
        lastname: \w+
        _format: html

UserBundle_consultant_delete:
    pattern: /{Id}/delete
    defaults:
        _controller: 'ExtiaUserBundle:AdminConsultant:delete'
        _format: html
    requirements:
        id: \d+
        _format: html
