UserBundle_consultant_timeline:
    pattern: /{userId}/{firstname}-{lastname}/timeline
    defaults:
        _controller: 'ExtiaUserBundle:Consultant:timeline'
        _format: html
    requirements:
        userId: \d+
        firstname: \w+
        lastname: \w+
        _format: html
