UserBundle_internal_list:
    pattern: /
    defaults:
        _controller: 'ExtiaUserBundle:AdminInternal:list'
        page: 1
    requirements:
        page: \d+

UserBundle_internal_timeline:
    pattern: /{Id}/{Url}/timeline
    defaults:
        _controller: 'ExtiaUserBundle:Internal:timeline'
        _format: html
        _menu: team
    requirements:
        Id: \d+
        _format: html





extia_user_manager_list:
    pattern: /manager/{page}
    defaults: { _controller: 'ExtiaUserBundle:Internal:list', page: 1 }
    requirements:
        page: \d+

extia_user_manager_new:
    pattern: /manager/new
    defaults: { _controller: 'ExtiaUserBundle:Internal:new' }

extia_user_manager_edit:
    pattern: /manager/{Id}/{Url}/edit
    defaults: { _controller: 'ExtiaUserBundle:Internal:edit' }
    requirements:
        id: \d+
        firstname: \w+
        lastname: \w+

extia_user_crh_list:
    pattern: /crh/{page}
    defaults: { _controller: 'ExtiaUserBundle:Crh:list', page: 1 }
    requirements:
        page: \d+

extia_user_crh_new:
    pattern: /crh/new
    defaults: { _controller: 'ExtiaUserBundle:Crh:new' }

extia_user_crh_edit:
    pattern: /crh/edit/{Id}/{Url}/edit
    defaults: { _controller: 'ExtiaUserBundle:Crh:edit' }
    requirements:
        id: \d+
        firstname: \w+
        lastname: \w+

extia_user_ajax_list:
    pattern: /manager/ajax-list
    defaults: { _controller: ExtiaUserBundle:Internal:listAjax }
