extia_user_management_create:
    pattern: /create
    defaults: { _controller: ExtiaUserBundle:Management:create }

extia_user_management_edit:
    pattern: /edit
    defaults: { _controller: ExtiaUserBundle:Management:edit }

extia_user_management_delete_consultant:
    pattern: /delete-consultant
    defaults: { _controller: ExtiaUserBundle:Management:deleteConsultant }

extia_user_management_delete_manager:
    pattern: /delete-manager
    defaults: { _controller: ExtiaUserBundle:Management:deleteManager }

extia_user_management_delete_crh:
    pattern: /delete-crh
    defaults: { _controller: ExtiaUserBundle:Management:deleteCrh }

extia_user_management_list_consultant:
    pattern: /list-consultant/{page}
    defaults: { _controller: ExtiaUserBundle:Management:listConsultant, page: 1 }

extia_user_management_list_manager:
    pattern: /list-manager
    defaults: { _controller: ExtiaUserBundle:Management:listManager, page: 1 }

extia_user_management_list_crh:
    pattern: /list-crh
    defaults: { _controller: ExtiaUserBundle:Management:listCrh, page: 1 }
