imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @GlorpenPropelBundle/Resources/config/config.yml }

framework:
    #esi: ~
    translator: { fallback: %locale% }
    secret: %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale: "%locale%"
    trusted_proxies: ~
    session:
        name: rhea_session
        cookie_lifetime: 1800
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'ExtiaDocumentBundle:Form:theme.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~
        less:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
    assets:
        # basic css compilation
        # compiled_css:
        #     output: css/compiled.css
        #     inputs:
        #         - %kernel.root_dir%/../vendor/twitter/bootstrap/less/bootstrap.less
        #         - %kernel.root_dir%/../vendor/bmatzner/fontawesome-bundle/Bmatzner/FontAwesomeBundle/Resources/public/css/font-awesome.css
        #     filters:
        #         - cssrewrite

        # responsive css compilation
        # responsive_css:
        #     output: css/responsive.css
        #     inputs:
        #         - %kernel.root_dir%/../vendor/twitter/bootstrap/less/responsive.less
        #     filters:
        #         - cssrewrite

        # all js compilation
        compiled_js:
            output: js/compiled.js
            inputs:
                - %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js
                - %kernel.root_dir%/../vendor/jquery/file-input/bootstrap.file-input.js


# Propel configuration
propel:
    build_properties:
        propel.useDateTimeClass: true
        propel.dateTimeClass: DateTime
        propel.defaultTimeStampFormat: null
        propel.defaultTimeFormat: null
        propel.defaultDateFormat: null

        propel.mysql.tableType: InnoDB

        propel.builder.pluralizer.class: builder.util.StandardEnglishPluralizer

    # db connections
    dbal:
        default_connection:           default
        connections:
            default:
                driver:               %database_driver%
                user:                 %database_user%
                password:             %database_password%
                dsn:                  %database_driver%:host=%database_host%;dbname=%database_name%;charset=UTF8
                options:              {}
                attributes:           {}

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# Gravatar bundle
ornicar_gravatar:
    rating: g
    size: 20
    default: monsterid

# Knp menu
knp_menu:
    twig:
        template: ExtiaMenuBundle:Menu:theme.html.twig

# Mopa
mopa_bootstrap:
    form:
        render_optional_text: false

# Group bundle
extia_group:
    managed_locales: %managed_locales%

# Task bundle
extia_task:
    documents:
        directory: "%kernel.root_dir%/../data/"

# Easy task
easy_task_workflow:
    workflows:
        # Crh Monitoring
        crh_monitoring:
            routes:
                prefix: /crh_monitoring
            actions:
                node:     nodeAction
                modal:    modalAction
                notify:   notificationAction
                timeline: timelineAction
            nodes:
                bootstrap:
                    bootstrap: true
                    route:      { pattern: "/bootstrap/{workflowId}" }
                    controller: { class:   Extia\Workflow\CrhMonitoringBundle\Controller\BootstrapNodeController }
                appointement:
                    route:      { pattern: "/appointement/{workflowId}" }
                    controller: { class:   Extia\Workflow\CrhMonitoringBundle\Controller\AppointementNodeController }
                meeting:
                    route:      { pattern: "/meeting/{workflowId}" }
                    controller: { class:   Extia\Workflow\CrhMonitoringBundle\Controller\MeetingNodeController }

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_pagination.html.twig
