imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @GlorpenPropelBundle/Resources/config/config.yml }

framework:
    #esi: ~
    translator: { fallback: %locale% }
    secret: %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale: "%locale%"
    trusted_proxies: ~
    session:
        name: rhea_session
        cookie_lifetime: 1800
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Propel configuration
propel:
    build_properties:
        propel.useDateTimeClass: true
        propel.dateTimeClass: DateTime
        propel.defaultTimeStampFormat: null
        propel.defaultTimeFormat: null
        propel.defaultDateFormat: null

        propel.mysql.tableType: InnoDB

        propel.builder.pluralizer.class: builder.util.StandardEnglishPluralizer

    # db connections
    dbal:
        default_connection:           default
        connections:
            default:
                driver:               %database_driver%
                user:                 %database_user%
                password:             %database_password%
                dsn:                  %database_driver%:host=%database_host%;dbname=%database_name%;charset=UTF8
                options:              {}
                attributes:           {}

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# Gravatar bundle
ornicar_gravatar:
    rating: g
    size: 20
    default: monsterid

# Knp menu
knp_menu:
    twig:
        template: ExtiaMenuBundle:Menu:theme.html.twig

# Mopa
mopa_bootstrap:
    form:
        render_optional_text: false

# Group bundle
extia_group:
    managed_locales: %managed_locales%

# Easy task
easy_task_workflow:
    workflows:

        # Crh Monitoring
        crh_monitoring:
            routes:
                prefix: /crh_monitoring
            actions:
                node:     nodeAction
                modal:    modalAction
                notify:   notificationAction
                timeline: timelineAction
            nodes:
                bootstrap:
                    bootstrap: true
                    route:      { pattern: "/bootstrap/{workflowId}" }
                    controller: { class:   Extia\Workflow\CrhMonitoringBundle\Controller\BootstrapNodeController }
                appointement:
                    route:      { pattern: "/appointement/{workflowId}" }
                    controller: { class:   Extia\Workflow\CrhMonitoringBundle\Controller\AppointementNodeController }
                meeting:
                    route:      { pattern: "/meeting/{workflowId}" }
                    controller: { class:   Extia\Workflow\CrhMonitoringBundle\Controller\MeetingNodeController }
