# ---------------------------------------
# Authentication
# ---------------------------------------
ExtiaUserBundle_login:
    resource: "@ExtiaUserBundle/Resources/config/routing/login.yml"
    prefix:   /

# ---------------------------------------
# Workflow management
# ---------------------------------------
EasyTaskWorkflowBundle_workflow:
    resource: "@EasyTaskWorkflowBundle/Resources/config/routing/workflow.yml"
    prefix:   /workflow

# ---------------------------------------
# Timeline routing
# ---------------------------------------
ExtiaTimelineBundle:
    resource: "@ExtiaTimelineBundle/Resources/config/routing.yml"
    prefix:   /timeline

Rhea_homepage:
    pattern: /
    defaults:
        _controller: ExtiaTimelineBundle:Timeline:userTimeline
        _format: html
