# ---------------------------------------
# Authentication
# ---------------------------------------
ExtiaUserBundle_login:
    resource: "@ExtiaUserBundle/Resources/config/routing/login.yml"
    prefix:   /

# ---------------------------------------
# Workflow management
# ---------------------------------------
EasyTaskWorkflowBundle_nodes:
    resource: .
    type: workflow_nodes
    defaults:
        _menu: dashboard

EasyTaskWorkflowBundle_workflow:
    resource: "@EasyTaskWorkflowBundle/Resources/config/routing/workflow.yml"
    prefix:   /task
    defaults:
        _menu: dashboard

ExtiaTaskBundle:
    resource: "@ExtiaTaskBundle/Resources/config/routing.yml"
    prefix:   /task
    defaults:
        _menu: dashboard

# ---------------------------------------
# Comments
# ---------------------------------------
ExtiaCommentBundle:
    resource: "@ExtiaCommentBundle/Resources/config/routing.yml"
    prefix:   /comment

# ---------------------------------------
# Search
# ---------------------------------------
ExtiaSearchBundle:
    resource: "@ExtiaSearchBundle/Resources/config/routing.yml"
    prefix:   /search

# ---------------------------------------
# Activity
# ---------------------------------------
ExtiaActivityBundle:
    resource: "@ExtiaActivityBundle/Resources/config/routing.yml"
    prefix:   /activity
    defaults:
        _menu: activity

# ---------------------------------------
# Group
# ---------------------------------------
ExtiaGroupBundle:
    resource: "@ExtiaGroupBundle/Resources/config/routing.yml"
    prefix:   /admin/group
    defaults:
        _menu: admin
        _submenu: group

# ---------------------------------------
# Users
# ---------------------------------------
ExtiaUserBundle_consultants:
    resource: "@ExtiaUserBundle/Resources/config/routing/consultant.yml"
    prefix:   /consultant
    defaults:
        _menu: consultant

ExtiaUserBundle_internal:
    resource: "@ExtiaUserBundle/Resources/config/routing/internal.yml"
    prefix:   /internal

# ---------------------------------------
# Home
# ---------------------------------------
Rhea_homepage:
    pattern: /
    defaults:
        _controller: ExtiaTaskBundle:Dashboard:userDashboard
        _format: html
        _menu: dashboard
