EasyTaskWorkflowBundle:
    resource: "@EasyTaskWorkflowBundle/Resources/config/routing.yml"
    prefix:   /

extia_front:
    resource: "@ExtiaFrontBundle/Resources/config/routing.yml"
    prefix:   /
