EasyTaskUserBundle:
    resource: "@EasyTaskUserBundle/Resources/config/routing/login.yml"
    prefix:   /

EasyTaskWorkflowBundle_workflow:
    resource: "@EasyTaskWorkflowBundle/Resources/config/routing/workflow.yml"
    prefix:   /

EasyTaskWorkflowBundle_timeline:
    resource: "@EasyTaskWorkflowBundle/Resources/config/routing/timeline.yml"
    prefix:   /

extia_front:
    resource: "@ExtiaFrontBundle/Resources/config/routing.yml"
    prefix:   /
