security:

    hide_user_not_found:  false

    encoders:
        Extia\Bundle\UserBundle\Model\User\Internal:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        extia:
            id: easy_task.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                provider:   extia
                check_path: easy_task_login_check
                login_path: easy_task_login
            logout:
                path:   easy_task_logout
                target: easy_task_login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_AUTHENTICATION] }
