crh_monitoring_bootstrap:
    pattern: /bootstrap/{workflowId}
    defaults:
        _controller: ExtiaWorkflowCrhMonitoringBundle:BootstrapNode:node
        _node: bootstrap

crh_monitoring_appointement:
    pattern: /appointement/{workflowId}
    defaults:
        _controller: ExtiaWorkflowCrhMonitoringBundle:AppointementNode:node
        _node: appointement

crh_monitoring_meeting:
    pattern: /meeting/{workflowId}
    defaults:
        _controller: ExtiaWorkflowCrhMonitoringBundle:MeetingNode:node
        _node: meeting
