Extia\Bundle\UserBundle\Model\Consultant:
    properties:
        firstname:
            - NotBlank: ~
        lastname:
            - NotBlank: ~
        job:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        crh_id:
            - NotNull: ~

Extia\Bundle\UserBundle\Model\Internal:
    properties:
        firstname:
            - NotBlank: ~
        lastname:
            - NotBlank: ~
        job:
            - NotBlank: ~
        trigram:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
