demo_say_hello:
    pattern: /demo/say_hello/{workflowId}
    defaults: { _controller: easy_task.type_node.say_hello:nodeAction }

demo_answer_hello:
    pattern: /demo/answer_hello/{workflowId}
    defaults: { _controller: easy_task.type_node.answer_hello:nodeAction }

demo_then_fight:
    pattern: /demo/then_fight/{workflowId}
    defaults: { _controller: easy_task.type_node.then_fight:nodeAction }
