parameters:
#    extia_agency.example.class: Extia\AgencyBundle\Example

services:
#    extia_agency.example:
#        class: %extia_agency.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
